import { Pressable, Text, View } from "react-native";
import { router } from "expo-router";
import { Shell, Card } from "../native/ui";
import { C } from "../native/theme";
import { useStore } from "../native/store";
import { CHAPTERS } from "../native/content";
export default function Planner(){
 const { premium, goal, due, mistakes, testHistory, todayCount } = useStore();
 if(!premium.active)return <Shell title="Study Planner" subtitle="Premium feature"><Card><Text style={{fontSize:20,fontWeight:"900",color:C.foreground}}>Premium access required</Text><Text style={{fontSize:12,color:C.mutedText,marginTop:7}}>Unlock the personalized Study Planner from BuzNeet Premium.</Text><Pressable onPress={()=>router.push("/premium")} style={{marginTop:14,padding:14,borderRadius:15,backgroundColor:C.primary,alignItems:"center"}}><Text style={{fontWeight:"900",color:C.primaryText}}>View Premium</Text></Pressable></Card></Shell>;
 const mistakeIds=Object.keys(mistakes); const recent=testHistory.slice(0,3); const focus=CHAPTERS.filter(c=>mistakeIds.some(id=>id.startsWith(c.id))).slice(0,3); const remaining=Math.max(0,goal-todayCount);
 const days=[["Today",due.length?"Complete "+Math.min(due.length,20)+" revision cards, then answer "+remaining+" practice questions.":"Complete your daily question goal, then review your mistakes."],["Tomorrow",focus[0]?"Focus on "+focus[0].name+": targeted practice followed by mistake review.":"Practice one weak chapter and finish a short timed test."],["Day 3",focus[1]?"Return to "+focus[1].name+" and test recall without notes.":"Do a mixed practice session and review difficult questions."],["Day 4",focus[2]?"Work on "+focus[2].name+", then revisit saved questions.":"Complete a subject-focused test and review errors."],["Day 5","Revision day: clear overdue cards and redo missed questions."],["Day 6","Timed practice: simulate exam conditions and analyse the report."],["Day 7",recent.length?"Weekly review: compare your latest "+recent.length+" test result"+(recent.length>1?"s":"")+" and set next targets.":"Weekly review: complete a timed test and analyse mistakes."]];
 return <Shell title="Study Planner" subtitle="Personalized weekly plan" right={<Pressable onPress={()=>router.back()}><Text style={{fontSize:24,color:C.foreground}}>×</Text></Pressable>}><Card style={{backgroundColor:C.primary,borderColor:C.primary}}><Text style={{fontSize:9,fontWeight:"900",letterSpacing:1,color:C.primaryText}}>THIS WEEK</Text><Text style={{fontSize:25,fontWeight:"900",color:C.primaryText,marginTop:5}}>{goal} questions/day</Text><Text style={{fontSize:11,color:C.primaryText,marginTop:5}}>{due.length} revision due · {mistakeIds.length} tracked mistakes · {testHistory.length} tests</Text></Card><Text style={{fontSize:18,fontWeight:"900",color:C.foreground,marginTop:20}}>Your plan</Text><View style={{gap:8,marginTop:10}}>{days.map(([day,detail],i)=><Card key={day}><View style={{flexDirection:"row"}}><View style={{width:35,height:35,borderRadius:12,backgroundColor:i===0?C.primary:C.muted,alignItems:"center",justifyContent:"center"}}><Text style={{fontWeight:"900",color:i===0?C.primaryText:C.foreground}}>{i+1}</Text></View><View style={{flex:1,marginLeft:11}}><Text style={{fontSize:13,fontWeight:"900",color:C.foreground}}>{day}{i===0?" · Start here":""}</Text><Text style={{fontSize:11,lineHeight:17,color:C.mutedText,marginTop:4}}>{detail}</Text></View></View></Card>)}</View></Shell>;
}