import{useState}from"react";import{Pressable,Text,View}from"react-native";import{router}from"expo-router";import{Shell,Card}from"../native/ui";import{C}from"../native/theme";import{useStore}from"../native/store";import{scheduleStudyNotifications,cancelStudyNotifications,prepareNotifications}from"../native/notifications";

const times=[[7,0,"7:00 AM"],[9,0,"9:00 AM"],[17,0,"5:00 PM"],[19,0,"7:00 PM"],[21,0,"9:00 PM"]];
export default function Settings(){
 const{goal,patch,telegramDone,notifications}=useStore();const[n,setN]=useState(notifications);const[saving,setSaving]=useState(false);
 const toggle=(key:"mission"|"revision"|"tests"|"streak")=>setN(x=>({...x,[key]:!x[key]}));
 const save=async()=>{setSaving(true);try{if(n.enabled)await prepareNotifications();else await cancelStudyNotifications();await scheduleStudyNotifications(n);patch({notifications:n});}finally{setSaving(false)}};
 return <Shell title="Settings" subtitle="Preferences" right={<Pressable onPress={()=>router.back()}><Text style={{fontSize:24,color:C.foreground}}>×</Text></Pressable>}>
  <Card><Text style={{fontSize:16,fontWeight:"900",color:C.foreground}}>Daily goal</Text><Text style={{fontSize:12,color:C.mutedText,marginTop:4}}>Questions to aim for each day</Text><View style={{flexDirection:"row",gap:8,marginTop:14}}>{[30,50,75,100].map(x=><Pressable key={x} onPress={()=>patch({goal:x})} style={{flex:1,paddingVertical:11,borderRadius:13,alignItems:"center",backgroundColor:goal===x?C.primary:C.muted}}><Text style={{fontWeight:"800",color:goal===x?C.primaryText:C.foreground}}>{x}</Text></Pressable>)}</View></Card>
  <Card style={{marginTop:12}}><Text style={{fontSize:16,fontWeight:"900",color:C.foreground}}>Study reminders</Text><Text style={{fontSize:12,color:C.mutedText,marginTop:4}}>Local reminders stay on this device. No notification server is required.</Text>
   <Pressable onPress={()=>setN(x=>({...x,enabled:!x.enabled}))} style={{marginTop:14,padding:13,borderRadius:14,backgroundColor:n.enabled?C.primary:C.muted}}><Text style={{fontWeight:"900",color:n.enabled?C.primaryText:C.foreground}}>{n.enabled?"Notifications enabled":"Notifications disabled"}</Text></Pressable>
   <Text style={{fontSize:10,fontWeight:"900",color:C.primary,marginTop:16}}>REMIND ME AT</Text><View style={{flexDirection:"row",gap:7,flexWrap:"wrap",marginTop:8}}>{times.map(([h,m,label])=><Pressable key={String(label)} onPress={()=>setN(x=>({...x,hour:h as number,minute:m as number}))} style={{paddingHorizontal:12,paddingVertical:9,borderRadius:12,borderWidth:1,borderColor:n.hour===h&&n.minute===m?C.primary:C.border,backgroundColor:n.hour===h&&n.minute===m?C.accent:C.card}}><Text style={{fontSize:11,fontWeight:"800",color:C.foreground}}>{label}</Text></Pressable>)}</View>
   <View style={{gap:7,marginTop:14}}>{[["mission","Daily mission"],["revision","Revision reminder"],["tests","Test reminder"],["streak","Streak reminder"]].map(([key,label])=><Pressable key={key} onPress={()=>toggle(key as any)} style={{padding:12,borderRadius:13,borderWidth:1,borderColor:C.border,flexDirection:"row",justifyContent:"space-between"}}><Text style={{fontSize:12,fontWeight:"800",color:C.foreground}}>{label}</Text><Text style={{fontSize:12,fontWeight:"900",color:(n as any)[key]?C.primary:C.mutedText}}>{(n as any)[key]?"ON":"OFF"}</Text></Pressable>)}</View>
   <Pressable disabled={saving} onPress={save} style={{marginTop:14,padding:14,borderRadius:15,backgroundColor:C.primary,alignItems:"center"}}><Text style={{fontWeight:"900",color:C.primaryText}}>{saving?"Saving…":"Save reminder settings"}</Text></Pressable>
  </Card>
  <Card style={{marginTop:12}}><Text style={{fontSize:16,fontWeight:"900",color:C.foreground}}>Telegram</Text><Text style={{fontSize:12,color:C.mutedText,marginTop:4}}>{telegramDone?"Community step completed":"Community step pending"}</Text></Card>
 </Shell>
}